# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8425167b8ab7f1154fc580c06e565087ffaa506ddb49329bc53eb6dd06c532d6e45c6b73c87a931528b8621aff466e2b23c62b3149281485b221822355cc44c7

test:
  secret_key_base: 51034c8bcb9fa7106102b12a9ce093bc5b776c29eaa8484fa80635f3d15cd585be0fa70e7eafe09007becc8497204caabfa4acf8a8b3c9586accdd651a58d2ee

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
